name: sherlock
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: alea <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: ^3.0.0-beta #'>=2.2.0 <2.3.0'
  angular_components: ^0.5.0-beta+1 #^0.2.2
  test: ^0.12.18+1
  less_dart: ^1.0.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- less_dart
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
